changelog: 
  categories: 
    - 
      labels: 
        - breaking-change
      title: "Breaking Changes 🛠"
    - 
      labels: 
        - feat
      title: "Exciting New Features 🎉"
    - 
      labels: 
        - fix
      title: Fixes
    - 
      labels: 
        - "*"
      title: "Other Changes"
  exclude: 
    labels: 
      - docs
